spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url-shortener
    username: developer
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
        use_sql_comments: true
        format_sql: true
  liquibase:
    contexts: dev
logging:
  level:
    root: INFO
    web: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
server:
  error:
    include-stacktrace: on_param