version: '3.8'
services:
  url-shortener-db-postgresql:
    image: postgres:14.2-alpine3.15
    environment:
      - POSTGRES_DB=url-shortener
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"